algoritmo "semnome"
// Função :
// Autor :
// Data : 17/05/2021
// Seção de Declarações
var
    celc, farie: Real
inicio
// Seção de Comandos
         Escreval("Programa de conversão de Temperatura")
         Escreval("")
         Escreva("Quantos ºF está fazendo hoje? ")
         Leia(farie)
         Escreval("")
         celc <- int((farie-32)/1.8)
         Escreval(farie, " ºF =", Celc, " ºC")
fimalgoritmo