algoritmo "semnome"
// Função :
// Autor :
// Data : 26/05/2021
// Seção de Declarações
var
feb, feb1, feb2, feb3, cont : inteiro
inicio
// Seção de Comandos
Escreva("Nº de elementos da sequencia de fibonacci: ")
leia(feb)
Escreval("")
feb1 <- 0
feb2 <- 1
Escreva(feb1, " ",feb2, " ")
para cont <- 3 ate feb passo 1 faca
     Feb3 <- feb1 + feb2
     escreva(feb3, " ")
     Feb1 <- feb2
     feb2 <- feb3
fimpara
fimalgoritmo
