algoritmo "Soma"
// Função :Somar dois Algarismos
// Autor : Rubens Lemos
// Data : 12/05/2021
// Seção de Declarações Solicitar dois numeros para serem somados
var
   n1, n2, soma: Inteiro
inicio
// Seção de Comandos 
   Escreva ("Escreva um numero inteiro: ")
   Leia (n1)
   Escreva ("Escreva outro numero inteiro: ")
   Leia(n2)
   soma<- n1 + n2
   Escreva ("A Soma de", n1, " +", n2, " =", soma)
fimalgoritmo
