algoritmo "semnome"
// Função :
// Autor :
// Data : 27/05/2021
// Seção de Declarações 
var
 X, Y : inteiro
 procedimento Soma(var A, B : inteiro)
 inicio
 A <- A + 1
 B <- B + 2
 Escreval("Recebi o valor", A)
 Escreval("Recebi o valor", B)
 Escreval("A soma de ",A , " +", B, " =", A+B)
 fimprocedimento
inicio
      X <- 5
      Y <- 3
      Soma(X, Y)
       Escreval("Enviei o valor", X)
       Escreval("Enviei o valor", Y)
fimalgoritmo
