algoritmo "semnome"
// Função :
// Autor :
// Data : 12/05/2021
// Seção de Declarações 
var
   a, b, c, d, f, g, h: real
inicio
// Seção de Comandos 
   Escreva("Digite uma Km qualquer: ")
   Leia(a)
   b <- a*10 //hm
   c <- b*10 //dam
   d <- c*10 //m
   f <- d*10 //dm
   g <- f*10 //cm
   h <- g*10 //mm
   Escreval("Esta Km equivale a: ")
   Escreval(b, " hm")
   Escreval(c, " dam")
   Escreval(d, " m")
   Escreval(f, " dm")
   Escreval(g, " cm")
   Escreval(h, " mm")
fimalgoritmo
